CREATE TABLE JdsStoreZonedDateTime(
	FieldId     NUMBER(19),
	Uuid  NVARCHAR2(48),
	Value       TIMESTAMP WITH TIME ZONE,
	PRIMARY KEY (FieldId,Uuid),
	FOREIGN KEY (Uuid) REFERENCES JdsEntityOverview(Uuid) ON DELETE CASCADE
)